"""add scripture references

Revision ID: 997d40992dc7
Revises: b527d2712f37
Create Date: 2026-06-15 08:00:27.252212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '997d40992dc7'
down_revision: Union[str, Sequence[str], None] = 'b527d2712f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripture_references',
    sa.Column('scripture_reference_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('source_type', sa.Enum('library_item_unit', 'sermon', name='scripturereferencessourcetype'), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('start_verse_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('end_verse_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('reference_text', sa.String(length=64), nullable=False),
    sa.Column('matched_text', sa.String(length=128), nullable=False),
    sa.Column('context_text', sa.String(length=512), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('display_order', mysql.SMALLINT(unsigned=True), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['end_verse_id'], ['bible_verses.verse_id'], name='fk_scripture_references_end_verse', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['start_verse_id'], ['bible_verses.verse_id'], name='fk_scripture_references_start_verse', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('scripture_reference_id')
    )
    op.create_index('idx_scripture_references_end_verse', 'scripture_references', ['end_verse_id'], unique=False)
    op.create_index('idx_scripture_references_source', 'scripture_references', ['source_type', 'source_id', 'display_order'], unique=False)
    op.create_index('idx_scripture_references_start_verse', 'scripture_references', ['start_verse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scripture_references_start_verse', table_name='scripture_references')
    op.drop_index('idx_scripture_references_source', table_name='scripture_references')
    op.drop_index('idx_scripture_references_end_verse', table_name='scripture_references')
    op.drop_table('scripture_references')
    # ### end Alembic commands ###
