"""Pydantic schemas shared by the backend and client package."""

from schemas.attachments import Attachment, PartialAttachment
from schemas.auth import (
    AuthDetailResponse,
    CsrfResponse,
    LoginRequest,
    TokenLoginRequest,
    TokenResponse,
    TokenRevokeResponse,
    UserResponse,
)
from schemas.base import APIModel
from schemas.sermons import (
    PatchedSermon,
    PartialSermonPassage,
    Sermon,
    SermonPassage,
    SermonSuggestionsResponse,
)
from schemas.verses import (
    BibleBook,
    BibleVerse,
    CommentaryEnd,
    CommentaryItem,
    CommentaryStart,
    CrossReferenceItem,
    CrossReferenceVerse,
    FootnoteCrossReferenceItem,
    FootnoteCrossReferenceVerse,
    PartialVerseNote,
    SearchIntentEnum,
    TestamentEnum,
    VerseCommentaryResponse,
    VerseCrossReferencesResponse,
    VerseNavigationTarget,
    VerseNote,
    VerseQueryResponse,
    VerseSearchResult,
    VerseSermonItem,
    VerseSermonResponse,
    VerseTextSearchResponse,
    VerseTranslationsResponse,
)
from schemas.widget import BibleWidget, PartialBibleWidget

__all__ = [
    "APIModel",
    "Attachment",
    "AuthDetailResponse",
    "BibleBook",
    "BibleVerse",
    "BibleWidget",
    "CommentaryEnd",
    "CommentaryItem",
    "CommentaryStart",
    "CrossReferenceItem",
    "CrossReferenceVerse",
    "CsrfResponse",
    "FootnoteCrossReferenceItem",
    "FootnoteCrossReferenceVerse",
    "LoginRequest",
    "PartialAttachment",
    "PartialBibleWidget",
    "PartialSermonPassage",
    "PartialVerseNote",
    "PatchedSermon",
    "SearchIntentEnum",
    "Sermon",
    "SermonPassage",
    "SermonSuggestionsResponse",
    "TestamentEnum",
    "TokenLoginRequest",
    "TokenResponse",
    "TokenRevokeResponse",
    "UserResponse",
    "VerseCommentaryResponse",
    "VerseCrossReferencesResponse",
    "VerseNavigationTarget",
    "VerseNote",
    "VerseQueryResponse",
    "VerseSearchResult",
    "VerseSermonItem",
    "VerseSermonResponse",
    "VerseTextSearchResponse",
    "VerseTranslationsResponse",
]
