"""Pydantic schemas shared by the backend and client package."""

from sermon_archive.schemas.attachments import Attachment, PartialAttachment
from sermon_archive.schemas.auth import (
    AuthDetailResponse,
    CsrfResponse,
    LoginRequest,
    TokenLoginRequest,
    TokenResponse,
    TokenRevokeResponse,
    UserResponse,
)
from sermon_archive.schemas.base import APIModel
from sermon_archive.schemas.library import (
    LibraryContentTypeEnum,
    LibraryItem,
    LibraryItemFile,
    LibraryItemUnit,
    LibraryUnitTypeEnum,
)
from sermon_archive.schemas.sermons import (
    PatchedSermon,
    Sermon,
    SermonSuggestionsResponse,
)
from sermon_archive.schemas.scripture import (
    PartialScriptureReference,
    ScriptureExtractionRequest,
    ScriptureExtractionResponse,
    ScriptureReference,
    ScriptureReferenceCreate,
    ScriptureReferenceSourceType,
    ScriptureReferenceUpdate,
    UnresolvedScriptureReference,
)
from sermon_archive.schemas.search import (
    SearchHit,
    SearchReferenceResponse,
    SearchResponse,
    SearchResultsResponse,
)
from sermon_archive.schemas.verses import (
    BibleBook,
    BibleVerse,
    CommentaryEnd,
    CommentaryItem,
    CommentaryStart,
    CrossReferenceItem,
    CrossReferenceVerse,
    FootnoteCrossReferenceItem,
    FootnoteCrossReferenceVerse,
    PartialVerseNote,
    TestamentEnum,
    VerseCommentaryResponse,
    VerseCrossReferencesResponse,
    VerseLibraryItemReferenceItem,
    VerseLibraryItemReferenceResponse,
    VerseNavigationTarget,
    VerseNote,
    VerseReferenceResponse,
    VerseReferenceText,
    VerseSermonItem,
    VerseSermonResponse,
    VerseTranslationsResponse,
)
from sermon_archive.schemas.widget import BibleWidget, PartialBibleWidget

__all__ = [
    "APIModel",
    "Attachment",
    "AuthDetailResponse",
    "BibleBook",
    "BibleVerse",
    "BibleWidget",
    "CommentaryEnd",
    "CommentaryItem",
    "CommentaryStart",
    "CrossReferenceItem",
    "CrossReferenceVerse",
    "CsrfResponse",
    "FootnoteCrossReferenceItem",
    "FootnoteCrossReferenceVerse",
    "LoginRequest",
    "LibraryContentTypeEnum",
    "LibraryItem",
    "LibraryItemFile",
    "LibraryItemUnit",
    "LibraryUnitTypeEnum",
    "PartialAttachment",
    "PartialBibleWidget",
    "PartialScriptureReference",
    "PartialVerseNote",
    "PatchedSermon",
    "Sermon",
    "SermonSuggestionsResponse",
    "ScriptureExtractionRequest",
    "ScriptureExtractionResponse",
    "ScriptureReference",
    "ScriptureReferenceCreate",
    "ScriptureReferenceSourceType",
    "ScriptureReferenceUpdate",
    "SearchHit",
    "SearchReferenceResponse",
    "SearchResponse",
    "SearchResultsResponse",
    "TestamentEnum",
    "TokenLoginRequest",
    "TokenResponse",
    "TokenRevokeResponse",
    "UserResponse",
    "UnresolvedScriptureReference",
    "VerseCommentaryResponse",
    "VerseCrossReferencesResponse",
    "VerseLibraryItemReferenceItem",
    "VerseLibraryItemReferenceResponse",
    "VerseNavigationTarget",
    "VerseNote",
    "VerseReferenceResponse",
    "VerseReferenceText",
    "VerseSermonItem",
    "VerseSermonResponse",
    "VerseTranslationsResponse",
]
